# Generated by Django 4.2.27 on 2025-12-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_block_id_alter_mininginfo_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_declared", models.BooleanField(default=False)),
            ],
        ),
    ]
